from datetime import date
from typing import Protocol

from textve.models import Change, DocumentSummary, FeedEvent, LegalDocument, Link, SearchHit


class DocumentStore(Protocol):
    def save_documents(self, docs: list[LegalDocument]) -> None: ...

    def get_document(self, doc_id: str) -> LegalDocument | None: ...

    def list_documents(self) -> list[DocumentSummary]: ...

    def search(self, query: str, limit: int) -> list[SearchHit]: ...


class LinkStore(Protocol):
    def save_links(self, links: list[Link]) -> None: ...

    def links(self, doc_id: str) -> tuple[list[Link], list[Link]]: ...


class ChangeStore(Protocol):
    def save_changes(self, changes: list[Change]) -> None: ...

    def changes(self, doc_id: str) -> list[Change]: ...

    def feed(self, after: int, since: date | None, limit: int) -> list[FeedEvent]: ...

    def recent_changes(
        self, before: int | None, source: str | None, status: str | None, limit: int
    ) -> list[FeedEvent]: ...
