from typing import Protocol

from textve.models import DocumentSummary, LegalDocument, Link, SearchHit


class DocumentStore(Protocol):
    def save_documents(self, docs: list[LegalDocument]) -> None: ...

    def delete_document(self, doc_id: str) -> None: ...

    def get_document(self, doc_id: str) -> LegalDocument | None: ...

    def list_documents(self) -> list[DocumentSummary]: ...

    def search(self, query: str, limit: int) -> list[SearchHit]: ...


class LinkStore(Protocol):
    def save_links(self, links: list[Link]) -> None: ...

    def links(self, doc_id: str) -> tuple[list[Link], list[Link]]: ...
